language: c
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get install libfreeimage-dev
script: 
  - cmake -G "Unix Makefiles" -H. -Bbuild
  - cmake --build build --target acbc --config Release
  - cd build
  - ctest
  - cd ..